name: 機能提案（Feature Request）
description: 新しい機能や改善のアイデアを提案
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        既存機能の改善や、新しい機能の提案を歓迎します。

  - type: textarea
    attributes:
      label: 実装したい機能の概要
      description: どのような機能を追加したいですか？
      placeholder: |
        例：
        - ～の情報を表示を改善してほしい
        - 〜するボタンを追加してほしい
    validations:
      required: true

  - type: textarea
    attributes:
      label: 背景・動機
      description: 解決したい課題などを記述してください。
      placeholder: |
        例：
        - 〜を確認したい
        - 〜を簡単にしたい
    validations:
      required: true

  - type: textarea
    attributes:
      label: 実装案（任意）
      description: もし具体的な実装のイメージがあれば記述してください。
      placeholder: |
        例：
        - 画像の横に～の情報を表示する
    validations:
      required: false

  - type: textarea
    attributes:
      label: 期待される動作・出力
      description: その機能が修正・実装された結果、ユーザーはどのような操作ができ、どのような結果が得られるべきですか？
    validations:
      required: true

  - type: textarea
    attributes:
      label: 補足事項
      description: その他、関係があると思われる情報があれば記述してください。
    validations:
      required: false
